---
name: JFD
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=2378ab78f953126cdad6ac0d2837f0f81b37639ad9caef248508184f3c2004d7
    ports:
      - 7575:7575
    restart: unless-stopped
  
  # jellyfin:
    # container_name: jellyfin
    # image: lscr.io/linuxserver/jellyfin:latest
    # environment:
      # - PUID=1000
      # - PGID=1000
      # - TZ=${TIMEZONE}
    # volumes:
      # - ${ROOT_DIR}/config/jellyfin-config:/config
      # - ${FILM_DIR}/movies:/movies
      # - ${TV_DIR}/tvshows:/tvshows

    # ports:
      # - "8096:8096"
    # restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/sonarr-config:/config
      - ${TV_DIR}/tvshows:/tvshows
      - ${ROOT_DIR}/data/downloads:/downloads

    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
#     - PUID=1000
#     - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/radarr-config:/config
      - ${FILM_DIR}/movies:/movies
      - ${ROOT_DIR}/data/downloads:/downloads

    ports:
      - 7878:7878
    restart: unless-stopped
    
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
#     - PUID=1000
#     - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/jellyseerr-config:/app/config
      - ${FILM_DIR}/movies:/movies
      - ${ROOT_DIR}/data/downloads:/downloads
    ports:
      - 5055:5055
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=${TIMEZONE}    
    volumes:
      - ${ROOT_DIR}/config/jackett-config:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT_DIR}/config/qbittorrent-config:/config
      - ${ROOT_DIR}/data/torrents:/data/torrents
      - ${ROOT_DIR}/data/downloads:/downloads
      - ${FILM_DIR}/movies:/movies
      - ${TV_DIR}/tvshows:/tvshows

    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # flaresolverr:
    # image: ghcr.io/flaresolverr/flaresolverr:latest
    # container_name: flaresolverr
    # environment:
      # - LOG_LEVEL=${LOG_LEVEL:-info}
      # - LOG_HTML=${LOG_HTML:-false}
      # - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      # - TZ=${TIMEZONE}
    # ports:
      # - 8191:8191
    # restart: unless-stopped